import { StyleSheet } from 'react-native';

type AppLayout = {
  phoneWidth: number;
  phoneHeight: number;
};

export const createAppStyles = ({ phoneWidth, phoneHeight }: AppLayout) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: '#0E0E0F',
    },
    background: {
      flex: 1,
      width: '100%',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      paddingVertical: 0,
      paddingHorizontal: 0,
      backgroundColor: '#050505',
    },
    phoneShell: {
      flex: 1,
      width: '100%',
      height: '100%',
      borderRadius: 0,
      backgroundColor: '#050505',
      padding: 0,
  
    },
    phoneFrame: {
      flex: 1,
      width: '100%',
      height: '100%',
      borderRadius: 0,
      backgroundColor: '#F6F6F7',
      overflow: 'hidden',
      paddingTop: 8,
      paddingHorizontal: 8,
      paddingBottom: 8,
    },
    notch: {
      position: 'absolute',
      top: 8,
      alignSelf: 'center',
      width: '30%',
      height: 28,
      borderRadius: 18,
      backgroundColor: '#050505',
      zIndex: 3,
    },
    statusRow: {
      marginTop: 6,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 8,
      marginBottom: 12,
      zIndex: 4,
    },
    timeText: {
      fontSize: 17,
      fontWeight: '700',
      color: '#6B6B6B',
      letterSpacing: 0.2,
    },
    statusIcons: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    statusGlyph: {
      fontSize: 16,
      color: '#2E2E30',
      fontWeight: '800',
    },
    statusGlyphSpacing: {
      marginLeft: 10,
    },
    toolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      position: 'relative',
      marginTop: 10,
      marginBottom: 14,
      zIndex: 4,
    },
    toolbarBrand: {
      flexDirection: 'row',
      alignItems: 'center',
      flexShrink: 0,
    },
    toolbarBrandLogo: {
      width: 34,
      height: 34,
      marginRight: 8,
    },
    toolbarCenterAbsolute: {
      position: 'absolute',
      left: 0,
      right: 0,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
    toolbarBrandName: {
      fontSize: 14,
      fontWeight: '800',
      color: '#1E1E21',
      textAlign: 'center',
      lineHeight: 18,
    },
    toolbarBrandSubtext: {
      fontSize: 11,
      fontWeight: '600',
      color: '#6D6D73',
      textAlign: 'center',
      lineHeight: 14,
    },
    toolbarButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: '#343436',
      alignItems: 'center',
      justifyContent: 'center',
    },
    toolbarSpacer: {
      flex: 1,
    },
    debugBanner: {
      marginHorizontal: 12,
      marginBottom: 8,
      borderRadius: 10,
      backgroundColor: '#111827',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: '#374151',
    },
    debugBannerText: {
      color: '#E5E7EB',
      fontSize: 11,
      lineHeight: 15,
    },
    debugBannerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 2,
    },
    debugBannerBullet: {
      color: '#93C5FD',
      fontSize: 10,
      fontWeight: '900',
    },
    scrollArea: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 4,
      paddingBottom: 18,
    },
    homeSection: {
      marginTop: 2,
    },
    moduleSection: {
      marginTop: 10,
    },
    sectionAnchor: {
      height: 1,
    },
    chipStickyHeader: {
      backgroundColor: '#F6F6F7',
      zIndex: 20,
      paddingTop: 8,
      paddingBottom: 10,
      marginBottom: 8,
      paddingHorizontal: 16,
    },
    chipRowSection: {
      backgroundColor: '#F6F6F7',
      zIndex: 20,
      paddingTop: 8,
      paddingBottom: 6,
      marginBottom: 6,
      paddingHorizontal: 10,
    },
    chipMapRowWrap: {
      paddingHorizontal: 10,
      marginBottom: 8,
    },
    chipRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 6,
      paddingRight: 24,
      marginBottom: 0,
    },
    chip: {
      minWidth: 104,
      height: 40,
      paddingHorizontal: 14,
      borderRadius: 20,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFFFFF',
    },
    chipSpacing: {
      marginRight: 8,
    },
    chipInactive: {
      borderColor: '#A8A8A8',
    },
    chipActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
      shadowColor: '#000',
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    chipText: {
      fontSize: 13,
      fontWeight: '500',
    },
    chipTextInactive: {
      color: '#3E3E3E',
    },
    chipTextActive: {
      color: '#F8F8F8',
    },
    selectedChipMapRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingRight: 4,
      paddingTop: 2,
    },
    selectedChipMapItem: {
      minWidth: 92,
      minHeight: 38,
      paddingHorizontal: 12,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
    },
    selectedChipMapItemSpacing: {
      marginRight: 8,
    },
    selectedChipMapItemInactive: {
      backgroundColor: '#FFFFFF',
      borderColor: '#D8D8DC',
    },
    selectedChipMapItemActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    selectedChipMapText: {
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'center',
    },
    selectedChipMapTextInactive: {
      color: '#2F2F31',
    },
    selectedChipMapTextActive: {
      color: '#FFFFFF',
    },
    moduleHeaderCard: {
      borderRadius: 18,
      backgroundColor: '#f6f6f7',
   
      padding: 14,
      marginBottom: 14,
    
    },
    moduleHeaderTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    moduleHeaderTextBlock: {
      flex: 1,
    },
    moduleHeaderTitle: {
      fontSize: 18,
      fontWeight: '900',
      color: '#131313',
      marginBottom: 4,
    },
    moduleHeaderSubtitle: {
      fontSize: 12,
      lineHeight: 17,
      color: '#5E5E62',
    },
    moduleHeaderBadge: {
      minWidth: 48,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: '#3F3F40',
      alignItems: 'center',
      justifyContent: 'center',
    },
    moduleHeaderBadgeText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '800',
    },
    moduleHeaderActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 12,
      gap: 10,
    },
    moduleWorkspace: {
      flexGrow: 1,
      justifyContent: 'center',
      paddingBottom: 8,
    },
    moduleNavButton: {
      flex: 1,
      minHeight: 42,
      borderRadius: 12,
      backgroundColor: '#F1F3F6',
      borderWidth: 1,
      borderColor: '#D9D9DD',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    moduleNavButtonText: {
      fontSize: 12.5,
      fontWeight: '800',
      color: '#2B2B2B',
    },
    enrollmentLeadStrip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingBottom: 8,
      marginBottom: 10,
      gap: 8,
    },
    leadCard: {
      width: 132,
      borderRadius: 14,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      padding: 10,
      marginRight: 8,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 7,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    leadCardActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    leadCardTitle: {
      fontSize: 12,
      fontWeight: '800',
      color: '#1C1C1C',
      marginBottom: 4,
    },
    leadCardTitleActive: {
      color: '#FFFFFF',
    },
    leadCardMeta: {
      fontSize: 10.5,
      lineHeight: 14,
      color: '#5B5B60',
      marginBottom: 2,
    },
    leadCardMetaActive: {
      color: '#EDEDED',
    },
    communicationToolbar: {
      marginBottom: 8,
    },
    timelineStrip: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingBottom: 8,
      marginBottom: 8,
      gap: 8,
    },
    timelineCard: {
      width: 132,
      borderRadius: 14,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      padding: 10,
      marginRight: 8,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 7,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    timelineCardActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    timelineCardDate: {
      fontSize: 10,
      fontWeight: '800',
      color: '#6A6A70',
      marginBottom: 4,
    },
    timelineCardDateActive: {
      color: '#EDEDED',
    },
    timelineCardName: {
      fontSize: 12,
      fontWeight: '800',
      color: '#1C1C1C',
      marginBottom: 4,
    },
    timelineCardNameActive: {
      color: '#FFFFFF',
    },
    timelineCardMeta: {
      fontSize: 10.5,
      lineHeight: 14,
      color: '#5B5B60',
      marginBottom: 2,
    },
    timelineCardMetaActive: {
      color: '#EDEDED',
    },
    tabStrip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    tabChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: '#F1F3F6',
      borderWidth: 1,
      borderColor: '#D9D9DD',
    },
    tabChipActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    tabChipText: {
      fontSize: 11.5,
      fontWeight: '800',
      color: '#2B2B2B',
    },
    tabChipTextActive: {
      color: '#FFFFFF',
    },
    teacherGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    teacherCard: {
      width: 132,
      borderRadius: 14,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      padding: 10,
      marginRight: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    teacherCardActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    teacherCardIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: '#F1F3F6',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
    },
    teacherCardIconText: {
      fontSize: 14,
      fontWeight: '900',
      color: '#2B2B2B',
    },
    teacherCardIconTextActive: {
      color: '#FFFFFF',
    },
    teacherCardName: {
      fontSize: 12,
      fontWeight: '800',
      color: '#1C1C1C',
      marginBottom: 4,
      textAlign: 'center',
    },
    teacherCardNameActive: {
      color: '#FFFFFF',
    },
    teacherCardMeta: {
      fontSize: 10.5,
      lineHeight: 14,
      color: '#5B5B60',
      textAlign: 'center',
    },
    teacherCardMetaActive: {
      color: '#EDEDED',
    },
    reportTable: {
      minWidth: 760,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E1E4EA',
      overflow: 'hidden',
      backgroundColor: '#f6f6f7',
      marginTop: 6,
    },
    reportTableHeader: {
      flexDirection: 'row',
      backgroundColor: '#F1F3F6',
      borderBottomWidth: 1,
      borderBottomColor: '#E1E4EA',
    },
    reportTableHeaderCell: {
      minWidth: 98,
      paddingVertical: 10,
      paddingHorizontal: 10,
      fontSize: 11,
      fontWeight: '800',
      color: '#202020',
    },
    reportTableRow: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderBottomColor: '#EEF1F4',
    },
    reportTableCell: {
      minWidth: 98,
      paddingVertical: 10,
      paddingHorizontal: 10,
      fontSize: 11,
      color: '#333333',
    },
    heroCard: {
      height: 196,
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: '#BFC3D4',
      marginBottom: 14,
      position: 'relative',
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 2,
    },
    heroGlow: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(120, 138, 186, 0.16)',
    },
    heroImage: {
      width: '100%',
      height: '100%',
    },
    sectionTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: '#171717',
      marginBottom: 10,
    },
    dashboardStickyHeader: {
      backgroundColor: '#F6F6F7',
      paddingTop: 4,
      paddingBottom: 10,
      marginBottom: 6,
      zIndex: 10,
    },
    grid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-start',
      alignContent: 'flex-start',
      maxHeight: 160,
      overflow: 'hidden',
      marginBottom: 14,
    },
    gridCard: {
      width: '22.5%',
      minHeight: 68,
      borderRadius: 12,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#ECECEC',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      paddingHorizontal: 6,
      marginBottom: 10,
      marginRight: 8,
      shadowColor: '#000',
      shadowOpacity: 0.035,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
      elevation: 1,
    },
    dashboardGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-start',
      gap: 8,
      marginBottom: 14,
    },
    dashboardGridScrollArea: {
      marginHorizontal: -6,
    },
    dashboardGridScroller: {
      paddingHorizontal: 4,
      marginBottom: 14,
    },
    dashboardGridColumn: {
      flexDirection: 'column',
    },
    dashboardGridColumnSpacing: {
      marginRight: 4,
    },
    dashboardGridCard: {
      width: Math.floor((phoneWidth - 24) / 3),
      minHeight: 104,
      borderRadius: 12,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#ECECEC',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 16,
      paddingHorizontal: 6,
      marginBottom: 14,
      marginRight: 0,
      shadowColor: '#000',
      shadowOpacity: 0.035,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
      elevation: 1,
    },
    dashboardGridCardActive: {
      backgroundColor: '#F7F8FA',
      borderColor: '#3F3F40',
    },
    gridIconWrap: {
      width: 28,
      height: 28,
      marginBottom: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    gridLabel: {
      fontSize: 10.5,
      textAlign: 'center',
      fontWeight: '700',
      color: '#171717',
      lineHeight: 14,
    },
    modulePanel: {
      marginTop: 16,
      marginBottom: 16,
      borderRadius: 18,
      backgroundColor: 'transparent',
      borderWidth: 0,
      borderColor: 'transparent',
      paddingTop: 18,
      paddingHorizontal: 0,
      paddingBottom: 14,
      overflow: 'hidden',
      shadowColor: 'transparent',
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffset: { width: 0, height: 0 },
      elevation: 0,
    },
    moduleHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      marginTop: 8,
      marginBottom: 10,
    },
    moduleTitle: {
      flex: 1,
      fontSize: 18,
      fontWeight: '900',
      color: '#131313',
    },
    modulePointsList: {
      gap: 10,
    },
    modulePointRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    modulePointDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginTop: 6,
      backgroundColor: '#3F3F40',
    },
    modulePointText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 19,
      color: '#444',
    },
    registerPanel: {
      marginBottom: 16,
      borderRadius: 16,
      backgroundColor: 'transparent',
      padding: 12,
    },
    leadDetailsSection: {
      marginBottom: 10,
    },
    leadDetailsTitle: {
      fontSize: 16,
      fontWeight: '900',
      color: '#111111',
      marginBottom: 8,
    },
    leadMetaStrip: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 8,
    },
    leadMetaPill: {
      flex: 1,
      borderRadius: 14,
      backgroundColor: '#F7F7F8',
      borderWidth: 1,
      borderColor: '#E4E4E8',
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    leadMetaLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: '#676767',
      marginBottom: 2,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    leadMetaValue: {
      fontSize: 12.5,
      fontWeight: '800',
      color: '#141414',
    },
    leadStatsRow: {
      flexDirection: 'row',
      gap: 8,
    },
    leadStatCard: {
      flex: 1,
      minHeight: 108,
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.06)',
    },
    leadStatCardGreen: {
      backgroundColor: '#D7E7CD',
    },
    leadStatCardYellow: {
      backgroundColor: '#F0EE96',
    },
    leadStatTextBlock: {
      flex: 1,
      paddingRight: 8,
    },
    leadStatNumber: {
      fontSize: 21,
      fontWeight: '900',
      color: '#111111',
      lineHeight: 24,
    },
    leadStatLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: '#222222',
      marginTop: 2,
    },
    leadStatFooter: {
      marginTop: 12,
      fontSize: 11.5,
      color: '#2A2A2A',
    },
    leadStatIconWrap: {
      width: 36,
      alignItems: 'flex-end',
      justifyContent: 'center',
    },
    leadReportCard: {
      width: '100%',
      maxWidth: 340,
      borderRadius: 18,
      backgroundColor: '#FFFFFF',
      padding: 16,
      borderWidth: 1,
      borderColor: '#E5E5EA',
    },
    leadReportRow: {
      borderRadius: 14,
      backgroundColor: '#F7F7F8',
      borderWidth: 1,
      borderColor: '#E4E4E8',
      padding: 12,
      marginBottom: 10,
    },
    leadReportName: {
      fontSize: 13.5,
      fontWeight: '900',
      color: '#111111',
      marginBottom: 4,
    },
    leadReportMeta: {
      fontSize: 11.5,
      color: '#404040',
      lineHeight: 15,
    },
    leadReportActionRow: {
      marginTop: 10,
      alignItems: 'flex-end',
    },
    leadReportActionButton: {
      minWidth: 118,
      borderRadius: 14,
      backgroundColor: '#3F3F40',
      paddingHorizontal: 14,
      paddingVertical: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    leadReportActionButtonText: {
      fontSize: 12.5,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    registerHeader: {
      marginBottom: 8,
    },
    registerTitle: {
      fontSize: 16,
      fontWeight: '900',
      color: '#111111',
      marginBottom: 3,
    },
    registerSubtitle: {
      fontSize: 11,
      color: '#707070',
      lineHeight: 15,
    },
    registerBody: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      alignItems: 'stretch',
    },
    formColumn: {
      flex: 1,
      minWidth: 0,
    },
    cameraColumn: {
      width: '100%',
      flexGrow: 1,
      minWidth: 0,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
     formRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 8,
    },
   inputGroup: {
      flex: 1,
      minWidth: 140,
    },
    fullWidthGroup: {
      minWidth: '100%',
    },
    inputLabel: {
      fontSize: 10.5,
      fontWeight: '800',
      color: '#444444',
      marginBottom: 5,
    },
    textInput: {
      minHeight: 40,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: '#BDBDC2',
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 12,
      paddingVertical: 9,
      color: '#111111',
      fontSize: 12.5,
    },
    datePickerField: {
      width: '100%',
      alignSelf: 'stretch',
      minHeight: 38,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#BDBDC2',
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 12,
      paddingVertical: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    datePickerValue: {
      flex: 1,
      color: '#111111',
      fontSize: 12.5,
    },
    datePickerPlaceholder: {
      color: '#A0A0A0',
    },
    multilineInput: {
      minHeight: 56,
      textAlignVertical: 'top',
    },
    photoUploadCard: {
      flexBasis: '100%',
      minHeight: 176,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E9E9EA',
      backgroundColor: '#F9FAFC',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 14,
    },
    photoCircle: {
      width: 70,
      height: 70,
      borderRadius: 35,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#3F3F40',
      marginBottom: 10,
    },
    photoPreview: {
      width: 88,
      height: 88,
      borderRadius: 44,
      overflow: 'hidden',
      marginBottom: 10,
      borderWidth: 2,
      borderColor: '#D9D9DD',
      backgroundColor: '#FFFFFF',
    },
    photoPreviewImage: {
      width: '100%',
      height: '100%',
    },
    photoCircleText: {
      color: '#FFFFFF',
      fontSize: 30,
      fontWeight: '300',
      lineHeight: 32,
    },
    photoLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: '#202020',
    },
    photoHint: {
      marginTop: 4,
      fontSize: 11,
      color: '#6B6B6B',
      textAlign: 'center',
    },
    registerSummaryCard: {
      flexBasis: '100%',
      borderRadius: 14,
      backgroundColor: '#F7F7F8',
      padding: 11,
      borderWidth: 1,
      borderColor: '#E2E2E6',
    },
    summaryTitle: {
      fontSize: 12.5,
      fontWeight: '900',
      color: '#131313',
      marginBottom: 7,
    },
    summaryText: {
      fontSize: 11,
      lineHeight: 15,
      color: '#404040',
      marginBottom: 2,
    },
    pillRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingBottom: 8,
      marginBottom: 4,
      gap: 8,
    },
    pill: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: '#F1F3F6',
      borderWidth: 1,
      borderColor: '#E0E4EA',
      marginRight: 8,
    },
    pillActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    counsellingToggle: {
      alignSelf: 'flex-start',
      marginTop: 4,
    },
    pillText: {
      fontSize: 11.5,
      fontWeight: '700',
      color: '#2C2C2C',
    },
    pillTextActive: {
      color: '#FFFFFF',
    },
    registerActions: {
      width: '100%',
      marginTop: 2,
      alignItems: 'flex-start',
    },
    enrollmentDocsSection: {
      flexBasis: '100%',
      borderRadius: 16,
      backgroundColor: '#F8FAFD',
      padding: 12,
      borderWidth: 1,
      borderColor: '#E4E8F0',
      marginBottom: 4,
    },
    enrollmentDocsTitle: {
      fontSize: 13,
      fontWeight: '800',
      color: '#131313',
      marginBottom: 10,
    },
    enrollmentDocsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 8,
    },
    enrollmentDocButton: {
      width: '48%',
      minHeight: 58,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#D9D9DD',
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 10,
      paddingVertical: 8,
      justifyContent: 'center',
    },
    enrollmentDocButtonLabel: {
      fontSize: 11.5,
      fontWeight: '800',
      color: '#202020',
      marginBottom: 2,
    },
    enrollmentDocButtonHint: {
      fontSize: 10.5,
      color: '#6B6B6B',
      lineHeight: 14,
    },
    registerButton: {
      minWidth: 150,
      width: '100%',
      paddingHorizontal: 16,
      paddingVertical: 11,
      borderRadius: 12,
      backgroundColor: '#3F3F40',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    registerButtonDisabled: {
      opacity: 0.7,
    },
    registerButtonText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    overlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(10, 10, 10, 0.34)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      zIndex: 50,
    },
    popupCard: {
      width: '100%',
      maxWidth: 320,
      borderRadius: 18,
      backgroundColor: '#FFFFFF',
      padding: 18,
      borderWidth: 1,
      borderColor: '#E7E7EA',
      shadowColor: '#000',
      shadowOpacity: 0.18,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 6,
    },
    popupTitle: {
      fontSize: 16,
      fontWeight: '900',
      color: '#131313',
      marginBottom: 8,
    },
    popupMessage: {
      fontSize: 12.5,
      lineHeight: 18,
      color: '#444444',
      marginBottom: 14,
    },
    popupActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 10,
    },
    popupButton: {
      minWidth: 90,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    popupButtonPrimary: {
      backgroundColor: '#3F3F40',
    },
    popupButtonSecondary: {
      backgroundColor: '#F1F3F6',
      borderWidth: 1,
      borderColor: '#D9D9DD',
    },
    popupButtonText: {
      fontSize: 12.5,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    popupButtonTextSecondary: {
      color: '#2B2B2B',
    },
    teacherPopupCard: {
      width: '100%',
      maxWidth: 350,
      borderRadius: 18,
      backgroundColor: '#FFFFFF',
      padding: 18,
      borderWidth: 1,
      borderColor: '#E7E7EA',
      shadowColor: '#000',
      shadowOpacity: 0.18,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 6,
    },
    teacherHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    teacherAvatar: {
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#3F3F40',
      marginRight: 12,
    },
    teacherAvatarText: {
      color: '#FFFFFF',
      fontSize: 20,
      fontWeight: '900',
    },
    teacherHeaderText: {
      flex: 1,
    },
    teacherTitle: {
      fontSize: 18,
      fontWeight: '900',
      color: '#131313',
      marginBottom: 4,
    },
    teacherSubtitle: {
      fontSize: 12.5,
      color: '#5E5E62',
      lineHeight: 17,
    },
    teacherDetailsList: {
      marginBottom: 14,
    },
    teacherDetailRow: {
      marginBottom: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      backgroundColor: '#F7F8FA',
      borderWidth: 1,
      borderColor: '#ECEEF3',
    },
    teacherDetailLabel: {
      fontSize: 10.5,
      fontWeight: '800',
      color: '#6A6A70',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 4,
    },
    teacherDetailValue: {
      fontSize: 13.5,
      fontWeight: '700',
      color: '#1F1F22',
      lineHeight: 18,
    },
    teacherActions: {
      flexDirection: 'row',
      gap: 10,
    },
    teacherActionButton: {
      flex: 1,
      minWidth: 0,
    },
    teacherLogoutButton: {
      marginTop: 10,
      backgroundColor: '#C63D4D',
    },
    teacherLogoutText: {
      color: '#FFFFFF',
      fontSize: 12.5,
      fontWeight: '800',
    },
    statusCardsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    statusCard: {
      flex: 1,
      minHeight: 108,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      shadowColor: '#000',
      shadowOpacity: 0.06,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    statusCardLeft: {
      marginRight: 8,
    },
    statusCardRight: {
      marginLeft: 8,
    },
    reportCardRow: {
      paddingBottom: 8,
      marginBottom: 6,
      gap: 8,
    },
    reportMiniCard: {
      width: 120,
      minHeight: 112,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E1E4EA',
      backgroundColor: '#FFFFFF',
      padding: 10,
      marginRight: 8,
      justifyContent: 'space-between',
      shadowColor: '#000',
      shadowOpacity: 0.05,
      shadowRadius: 7,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    reportMiniCardActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    reportMiniIconWrap: {
      width: 28,
      height: 28,
      marginBottom: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    reportMiniTitle: {
      fontSize: 11,
      fontWeight: '800',
      color: '#1E1E1E',
      marginBottom: 2,
    },
    reportMiniTitleActive: {
      color: '#FFFFFF',
    },
    reportMiniSubtitle: {
      fontSize: 10,
      lineHeight: 14,
      color: '#5D5D61',
    },
    reportMiniSubtitleActive: {
      color: '#F7F7F7',
    },
    reportList: {
      marginTop: 6,
      gap: 10,
    },
    reportRowCard: {
      borderRadius: 14,
      backgroundColor: '#F8FAFD',
      borderWidth: 1,
      borderColor: '#E4E8F0',
      padding: 12,
    },
    reportRowTitle: {
      fontSize: 13,
      fontWeight: '800',
      color: '#131313',
      marginBottom: 4,
    },
    reportRowMeta: {
      fontSize: 11,
      color: '#454545',
      lineHeight: 16,
      marginBottom: 2,
    },
    statusCardText: {
      flex: 1,
      paddingRight: 8,
    },
    statusTitleRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      flexWrap: 'wrap',
    },
    statusNumber: {
      fontSize: 18,
      fontWeight: '900',
      color: '#111111',
      marginRight: 4,
    },
    statusSubtitle: {
      fontSize: 12.5,
      fontWeight: '500',
      color: '#252525',
      lineHeight: 18,
    },
    statusFooter: {
      marginTop: 20,
      fontSize: 12.5,
      fontWeight: '500',
      color: '#2B2B2B',
    },
    statusActionButton: {
      marginTop: 8,
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#D8D8DC',
    },
    statusActionLink: {
      fontSize: 11.5,
      fontWeight: '800',
      color: '#0A3D62',
    },
    statusIconWrap: {
      width: 34,
      alignItems: 'flex-end',
      justifyContent: 'center',
      paddingTop: 2,
    },
    campaignSummaryCard: {
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 12,
      marginBottom: 14,
      shadowColor: '#000',
      shadowOpacity: 0.05,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    campaignSummaryRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
    },
    campaignSummaryItem: {
      flex: 1,
      paddingRight: 10,
      borderRightWidth: 1,
      borderRightColor: '#ECEEF2',
      minHeight: 84,
      justifyContent: 'space-between',
    },
    campaignSummaryItemTotal: {
      borderRightWidth: 0,
      paddingRight: 0,
      paddingLeft: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    campaignSummaryValue: {
      fontSize: 22,
      fontWeight: '900',
      color: '#111111',
      lineHeight: 24,
    },
    campaignSummaryTotalValue: {
      fontSize: 24,
      fontWeight: '900',
      color: '#111111',
      lineHeight: 26,
      marginTop: 2,
      marginBottom: 2,
    },
    campaignSummaryTotalLabel: {
      fontSize: 12,
      fontWeight: '800',
      color: '#1D1D1F',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    campaignSummaryMini: {
      fontSize: 10.5,
      fontWeight: '600',
      color: '#5B5B61',
      marginTop: 2,
    },
    campaignSummaryLabel: {
      fontSize: 11.5,
      fontWeight: '700',
      color: '#2A2A2E',
      lineHeight: 15,
      marginTop: 4,
    },
    campaignSummaryDate: {
      marginTop: 10,
      fontSize: 11,
      color: '#75757B',
      fontWeight: '500',
      textAlign: 'right',
    },
    enrollmentTimelineScroll: {
      maxHeight: 250,
    },
    enrollmentTimelineList: {
      gap: 10,
      paddingBottom: 10,
    },
    enrollmentTimelineItem: {
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      paddingVertical: 12,
      paddingHorizontal: 12,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 7,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    enrollmentTimelineItemActive: {
      backgroundColor: '#F3F5F8',
      borderColor: '#3F3F40',
    },
    enrollmentTimelineConnector: {
      position: 'absolute',
      left: 28,
      top: 56,
      bottom: -10,
      width: 1,
      backgroundColor: '#D7DCE3',
    },
    enrollmentTimelineRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    enrollmentTimelineDate: {
      width: 74,
      paddingRight: 8,
    },
    enrollmentTimelineDateText: {
      fontSize: 10.5,
      fontWeight: '800',
      color: '#4A4A4F',
      marginBottom: 2,
    },
    enrollmentTimelineTimeText: {
      fontSize: 10,
      color: '#6A6A70',
    },
    enrollmentLeadAvatar: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: '#EDF0F4',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
      marginTop: 2,
    },
    enrollmentTimelineDetails: {
      flex: 1,
    },
    enrollmentTimelineStatus: {
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      marginBottom: 8,
    },
    enrollmentStatusRegistered: {
      backgroundColor: '#D9EAD3',
    },
    enrollmentStatusCancelled: {
      backgroundColor: '#F4D7DA',
    },
    enrollmentTimelineStatusText: {
      fontSize: 10,
      fontWeight: '900',
      color: '#323236',
      letterSpacing: 0.4,
    },
    enrollmentTimelineName: {
      fontSize: 12.5,
      fontWeight: '800',
      color: '#1D1D1F',
      marginBottom: 4,
    },
    enrollmentTimelineMeta: {
      fontSize: 11,
      color: '#4C4C52',
      lineHeight: 16,
    },
    enrollmentTimelineMetaBold: {
      fontWeight: '800',
      color: '#1F1F22',
    },
    footer: {
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingTop: 0,
      paddingBottom: 0,
      paddingHorizontal: 8,
      backgroundColor: '#f6f6f7',
      borderTopWidth: 1,
      borderTopColor: '#ECECF0',
    },
    footerNav: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      marginBottom: 0,
      paddingHorizontal: 2,
    },
    footerNavItem: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 38,
    },
    footerNavLabel: {
      marginTop: 0,
      fontSize: 7.5,
      color: '#111111',
      fontWeight: '700',
    },
    footerNavLabelMuted: {
      marginTop: 0,
      fontSize: 7.5,
      color: '#B0B0B5',
      fontWeight: '700',
    },
    footerAddButton: {
      width: 48,
      height: 26,
      borderRadius: 13,
      backgroundColor: '#F14A40',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#E53D33',
      marginBottom: 1,
      shadowColor: '#000',
      shadowOpacity: 0.12,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    poweredBy: {
      fontSize: 7.5,
      color: '#8A8A8A',
      fontWeight: '500',
      marginRight: 4,
    },
    logo: {
      width: 46,
      height: 28,
    },
    footerBrandRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 0,
      marginBottom: 0,
    },   
    homeIndicator: {
      alignSelf: 'center',
      width: 78,
      height: 2,
      borderRadius: 999,
      backgroundColor: '#f13232ff',
      marginTop: -1,
      marginBottom: 0,
    },
  });
